export const ADD_FILTER = 'ADD_FILTER'
export const SET_ORDER = 'SET_ORDER'
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const CLEAR_FILTER = 'CLEAR_FILTER'
export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE'

export const REQUEST_CHARACTER_LIST = 'REQUEST_CHARACTER_LIST'
export const SUCCESS_CHARACTER_LIST = 'SUCCESS_CHARACTER_LIST'
export const ERROR_CHARACTER_LIST = 'ERROR_CHARACTER_LIST'

export const REQUEST_CHARACTER_DETAIL = 'REQUEST_CHARACTER_DETAIL'
export const SUCCESS_CHARACTER_DETAIL = 'SUCCESS_CHARACTER_DETAIL'
export const ERROR_CHARACTER_DETAIL = 'ERROR_CHARACTER_DETAIL'

export const REQUEST_FILM_LIST = 'REQUEST_FILM_LIST'
export const SUCCESS_FILM_LIST = 'SUCCESS_FILM_LIST'
export const ERROR_FILM_LIST = 'ERROR_FILM_LIST'

export const REQUEST_CHARACTER_HOME = 'REQUEST_CHARACTER_HOME'
export const SUCCESS_CHARACTER_HOME = 'SUCCESS_CHARACTER_HOME'
export const ERROR_CHARACTER_HOME = 'ERROR_CHARACTER_HOME'

export const SUCCESS_SEARCH = 'SUCCESS_SEARCH'

export const SUCCESS_SPECIES = 'SUCCESS_SPECIES'
export const ERROR_SPECIES = 'ERROR_SPECIES'
